<?php

namespace NativeBlade\Commands\Config;

use Illuminate\Console\Command;

class AndroidConfigGenerator
{
    public function __construct(private Command $cmd) {}

    private const START_XML = '<!-- nativeblade:config:start -->';
    private const END_XML = '<!-- nativeblade:config:end -->';

    public function generate(array $config): void
    {
        $this->generateTheme($config);
        $this->generateOrientation($config);
        $this->generateEdgeToEdge();
        $this->generateVersion($config);
        $this->generateSdk($config);
        $this->generateProguard();
        $this->stripDebugSymbolsBlock();
        $this->generatePushNotification($config);
    }

    /**
     * Tauri's release builds enable minification + ProGuard, which strips
     * methods called via JNI from Rust (`Rust.onActivityCreate`, etc.) and
     * crashes the app at activity create with a JavaException.
     *
     * Patch the user's proguard-rules.pro with the keep rules NativeBlade
     * needs, between markers so the dev's own rules outside the block are
     * preserved.
     */
    private function generateProguard(): void
    {
        $path = base_path('src-tauri/gen/android/app/proguard-rules.pro');
        if (!file_exists($path)) return;

        $packageName = $this->detectPackageName();
        $startMarker = '# nativeblade:proguard:start';
        $endMarker = '# nativeblade:proguard:end';

        $rules = <<<RULES
{$startMarker}
# Tauri runtime + Wry WebView bindings
-keep class app.tauri.** { *; }

# Activity wrapper + Rust JNI bridge generated by Wry
-keep class {$packageName}.** { *; }
-keepclassmembers class {$packageName}.** { *; }

# NativeBlade plugins (push, media)
-keep class app.nativeblade.** { *; }
-keepclassmembers class app.nativeblade.** { *; }

# Firebase (used by push plugin)
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }

# WebView JavaScript interfaces
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# Native JNI methods
-keepclasseswithmembers class * {
    native <methods>;
}
{$endMarker}
RULES;

        $content = file_get_contents($path);

        $startQ = preg_quote($startMarker, '/');
        $endQ = preg_quote($endMarker, '/');
        $pattern = "/[ \t]*{$startQ}.*?{$endQ}/s";

        if (preg_match($pattern, $content)) {
            $content = preg_replace($pattern, $rules, $content);
        } else {
            $content = rtrim($content) . "\n\n" . $rules . "\n";
        }

        file_put_contents($path, $content);
        $this->cmd->line("  <fg=green>✓</> proguard-rules.pro patched");
    }

    private function detectPackageName(): string
    {
        $manifestPath = base_path('src-tauri/gen/android/app/src/main/AndroidManifest.xml');
        if (file_exists($manifestPath)) {
            $manifest = file_get_contents($manifestPath);
            if (preg_match('/package="([^"]+)"/', $manifest, $m)) return $m[1];
        }

        $gradlePath = base_path('src-tauri/gen/android/app/build.gradle.kts');
        if (file_exists($gradlePath)) {
            $gradle = file_get_contents($gradlePath);
            if (preg_match('/namespace\s*=\s*"([^"]+)"/', $gradle, $m)) return $m[1];
        }

        return 'com.example.app';
    }

    /**
     * Single source of truth for everything written to themes.xml: status
     * bar color/style, navigation bar color, fullscreen, splash background.
     * Items are wrapped in `<!-- nativeblade:config -->` markers — anything
     * outside the markers (custom items the dev added manually) stays put.
     */
    private function generateTheme(array $config): void
    {
        $themePath = base_path('src-tauri/gen/android/app/src/main/res/values/themes.xml');
        if (!file_exists($themePath)) return;

        $themeName = $this->detectThemeName();
        $items = $this->buildThemeItems($config);

        foreach ([$themePath, str_replace('/values/', '/values-night/', $themePath)] as $path) {
            if (!file_exists($path)) {
                $this->writeFreshTheme($path, $themeName, $items);
                continue;
            }

            $xml = file_get_contents($path);
            $xml = $this->upsertThemeItems($xml, $themeName, $items);
            file_put_contents($path, $xml);
        }

        $this->cmd->line("  <fg=green>✓</> Android theme: " . count($items) . " items");
    }

    /**
     * `android:statusBarColor` and `android:navigationBarColor` map to
     * `Window.setStatusBarColor` / `setNavigationBarColor`, both deprecated
     * in Android 15 and ignored under edge-to-edge. We only emit the light
     * icon flags here; the bars are made transparent by `enableEdgeToEdge()`
     * in MainActivity (see generateEdgeToEdge). Devs who still want a
     * visible color paint it inside the WebView via CSS using safe-area
     * insets, since the system bars sit over the content.
     */
    private function buildThemeItems(array $config): array
    {
        $items = [];

        if (isset($config['statusBar'])) {
            $light = ($config['statusBar']['style'] ?? 'dark') === 'light' ? 'true' : 'false';
            $items[] = '<item name="android:windowLightStatusBar" tools:targetApi="23">' . $light . '</item>';
        }

        if (isset($config['navigationBar'])) {
            $navStyle = $config['navigationBar']['style']
                ?? ($config['statusBar']['style'] ?? 'dark');
            $light = $navStyle === 'light' ? 'true' : 'false';
            $items[] = '<item name="android:windowLightNavigationBar" tools:targetApi="27">' . $light . '</item>';
        }

        if (isset($config['fullscreen'])) {
            $items[] = '<item name="android:windowFullscreen">' . ($config['fullscreen'] ? 'true' : 'false') . '</item>';
        }

        if (isset($config['splashBackground'])) {
            $color = $this->normalizeArgb($config['splashBackground']);
            $items[] = '<item name="android:windowSplashScreenBackground">' . $color . '</item>';
        }

        return $items;
    }

    private function normalizeArgb(string $color): string
    {
        return str_starts_with($color, '#FF') ? $color : '#FF' . ltrim($color, '#');
    }

    private function writeFreshTheme(string $path, string $themeName, array $items): void
    {
        $body = empty($items) ? '' : "\n        " . implode("\n        ", $items);
        $xml = <<<XML
<resources xmlns:tools="http://schemas.android.com/tools">
    <style name="{$themeName}" parent="Theme.MaterialComponents.DayNight.NoActionBar">
        {$this->markerOpen()}{$body}
        {$this->markerClose()}
    </style>
</resources>
XML;
        @mkdir(dirname($path), 0755, true);
        file_put_contents($path, $xml);
    }

    private function upsertThemeItems(string $xml, string $themeName, array $items): string
    {
        $body = empty($items) ? '' : "\n        " . implode("\n        ", $items);
        $newBlock = $this->markerOpen() . $body . "\n        " . $this->markerClose();

        $startQ = preg_quote(self::START_XML, '/');
        $endQ = preg_quote(self::END_XML, '/');
        $pattern = "/[ \t]*{$startQ}.*?{$endQ}/s";

        if (preg_match($pattern, $xml)) {
            return preg_replace($pattern, $newBlock, $xml);
        }

        $itemPattern = '/<item name="android:(statusBarColor|navigationBarColor|windowLightStatusBar|windowLightNavigationBar|windowFullscreen|windowSplashScreenBackground)"[^>]*>[^<]*<\/item>\s*/';
        $xml = preg_replace($itemPattern, '', $xml);

        if (preg_match('/<style name="' . preg_quote($themeName, '/') . '"[^>]*>/', $xml)) {
            return preg_replace(
                '/(<style name="' . preg_quote($themeName, '/') . '"[^>]*>)/',
                "$1\n        {$newBlock}",
                $xml,
                1
            );
        }

        return $xml;
    }

    private function markerOpen(): string
    {
        return self::START_XML;
    }

    private function markerClose(): string
    {
        return self::END_XML;
    }

    private function detectThemeName(): string
    {
        $manifestPath = base_path('src-tauri/gen/android/app/src/main/AndroidManifest.xml');
        if (!file_exists($manifestPath)) return 'Theme.nativeblade';

        $manifest = file_get_contents($manifestPath);
        if (preg_match('/android:theme="@style\/([^"]+)"/', $manifest, $matches)) {
            return $matches[1];
        }

        return 'Theme.nativeblade';
    }

    /**
     * Activity attribute, not a child element — can't wrap with comments.
     * Set when defined; remove the attribute entirely when not.
     */
    private function generateOrientation(array $config): void
    {
        $manifestPath = base_path('src-tauri/gen/android/app/src/main/AndroidManifest.xml');
        if (!file_exists($manifestPath)) return;

        $manifest = file_get_contents($manifestPath);
        $orientation = $config['orientation'] ?? null;

        if ($orientation === null) {
            $manifest = preg_replace('/\s*android:screenOrientation="[^"]*"/', '', $manifest);
            file_put_contents($manifestPath, $manifest);
            return;
        }

        $androidOrientation = match ($orientation) {
            'portrait' => 'portrait',
            'landscape' => 'landscape',
            'auto', 'unspecified' => 'unspecified',
            default => 'portrait',
        };

        if (str_contains($manifest, 'android:screenOrientation')) {
            $manifest = preg_replace(
                '/android:screenOrientation="[^"]*"/',
                'android:screenOrientation="' . $androidOrientation . '"',
                $manifest
            );
        } else {
            $manifest = preg_replace(
                '/<activity\b/',
                '<activity android:screenOrientation="' . $androidOrientation . '"',
                $manifest,
                1
            );
        }

        file_put_contents($manifestPath, $manifest);
        $this->cmd->line("  <fg=green>✓</> Android orientation: {$androidOrientation}");

        if ($androidOrientation !== 'unspecified') {
            $this->cmd->line("  <fg=yellow>→</> Android 16+ ignores screenOrientation on foldables and large-screen devices, test layout responsively");
        }
    }

    /**
     * Safety net for the Play Console "edge-to-edge may not be available"
     * warning. Recent Tauri scaffolds already inject `enableEdgeToEdge()`
     * in MainActivity.kt; this patch covers older scaffolds (e.g. apps
     * shipped before that template change) and projects where the dev
     * removed the call.
     *
     * Skip silently when an existing `enableEdgeToEdge()` or
     * `setDecorFitsSystemWindows` call is detected so we don't fight a
     * dev who customized the activity.
     */
    private function generateEdgeToEdge(): void
    {
        $mainActivity = $this->findMainActivity();
        if (!$mainActivity) return;

        $content = file_get_contents($mainActivity);

        if (preg_match('/\benableEdgeToEdge\s*\(/', $content)
            || preg_match('/\bsetDecorFitsSystemWindows\s*\(/', $content)) {
            return;
        }

        $startMarker = '// nativeblade:edgetoedge:start';
        $endMarker = '// nativeblade:edgetoedge:end';

        $block = "    {$startMarker}\n"
            . "    override fun onCreate(savedInstanceState: android.os.Bundle?) {\n"
            . "        super.onCreate(savedInstanceState)\n"
            . "        androidx.core.view.WindowCompat.setDecorFitsSystemWindows(window, false)\n"
            . "    }\n"
            . "    {$endMarker}";

        $startQ = preg_quote($startMarker, '/');
        $endQ = preg_quote($endMarker, '/');

        if (preg_match("/[ \t]*{$startQ}.*?{$endQ}/s", $content)) {
            $content = preg_replace("/[ \t]*{$startQ}.*?{$endQ}/s", ltrim($block), $content);
        } elseif (preg_match('/class\s+MainActivity\s*:\s*TauriActivity\s*\(\s*\)\s*$/m', $content)) {
            $content = preg_replace(
                '/(class\s+MainActivity\s*:\s*TauriActivity\s*\(\s*\))(\s*)$/m',
                "$1 {\n{$block}\n}\n",
                $content,
                1
            );
        } elseif (preg_match('/class\s+MainActivity\s*:\s*TauriActivity\s*\(\s*\)\s*\{/', $content)) {
            $content = preg_replace(
                '/(class\s+MainActivity\s*:\s*TauriActivity\s*\(\s*\)\s*\{)/',
                "$1\n{$block}\n",
                $content,
                1
            );
        } else {
            $this->cmd->line("  <fg=yellow>→</> MainActivity.kt has unexpected shape, skip edge-to-edge patch");
            return;
        }

        file_put_contents($mainActivity, $content);
        $this->cmd->line("  <fg=green>✓</> MainActivity.kt: edge-to-edge enabled");
    }

    private function findMainActivity(): ?string
    {
        $base = base_path('src-tauri/gen/android/app/src/main/java');
        if (!is_dir($base)) return null;

        $iter = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($base));
        foreach ($iter as $file) {
            if ($file->isFile() && $file->getFilename() === 'MainActivity.kt') {
                return $file->getPathname();
            }
        }
        return null;
    }

    private function generateVersion(array $config): void
    {
        if (!isset($config['version']) || !isset($config['buildNumber'])) return;

        $gradlePath = base_path('src-tauri/gen/android/app/build.gradle.kts');
        if (!file_exists($gradlePath)) return;

        $gradle = file_get_contents($gradlePath);

        if (str_contains($gradle, 'versionCode')) {
            $gradle = preg_replace('/versionCode\s*=\s*\d+/', 'versionCode = ' . $config['buildNumber'], $gradle);
            $gradle = preg_replace('/versionName\s*=\s*"[^"]*"/', 'versionName = "' . $config['version'] . '"', $gradle);
        }

        file_put_contents($gradlePath, $gradle);
        $this->cmd->line("  <fg=green>✓</> Android version: {$config['version']} ({$config['buildNumber']})");
    }

    /**
     * Strip any leftover `ndk { debugSymbolLevel = ... }` block from
     * `build.gradle.kts`. Earlier versions of NativeBlade added this expecting
     * AGP to extract native debug symbols into `BUNDLE-METADATA/`. In practice
     * AGP only processes libs Gradle compiles itself (CMake/ndk-build); it
     * silently ignores pre-built libs under `jniLibs/`, which is how Tauri
     * ships the Rust binary. The block did nothing useful and was misleading.
     *
     * Stripping (`strip = "debuginfo"`) is now done at the Rust profile level
     * in `Cargo.toml`. See `stubs/Cargo.toml.stub`.
     */
    private function stripDebugSymbolsBlock(): void
    {
        $gradlePath = base_path('src-tauri/gen/android/app/build.gradle.kts');
        if (!file_exists($gradlePath)) return;

        $gradle = file_get_contents($gradlePath);
        if (!str_contains($gradle, 'debugSymbolLevel')) return;

        $stripped = preg_replace(
            '/\n\s*ndk\s*\{\s*debugSymbolLevel\s*=\s*"[^"]*"\s*\}\n?/',
            "\n",
            $gradle
        );

        file_put_contents($gradlePath, $stripped);
        $this->cmd->line("  <fg=green>✓</> Removed legacy debugSymbolLevel block (AGP ignores Tauri's jniLibs)");
    }

    private function generateSdk(array $config): void
    {
        $gradlePath = base_path('src-tauri/gen/android/app/build.gradle.kts');
        if (!file_exists($gradlePath)) return;

        $gradle = file_get_contents($gradlePath);
        $changed = false;

        if (isset($config['minSdk'])) {
            $gradle = preg_replace('/minSdk\s*=\s*\d+/', 'minSdk = ' . $config['minSdk'], $gradle);
            $changed = true;
        }

        if (isset($config['targetSdk'])) {
            $gradle = preg_replace('/targetSdk\s*=\s*\d+/', 'targetSdk = ' . $config['targetSdk'], $gradle);
            $changed = true;
        }

        if ($changed) {
            file_put_contents($gradlePath, $gradle);
            $this->cmd->line("  <fg=green>✓</> Android SDK: min=" . ($config['minSdk'] ?? '?') . " target=" . ($config['targetSdk'] ?? '?'));
        }
    }

    private function generatePushNotification(array $config): void
    {
        $push = $config['notification'] ?? null;
        if (!$push || !isset($push['fcmConfig'])) return;

        $source = $push['fcmConfig'];
        if (!file_exists($source)) {
            $this->cmd->line("  <fg=yellow>→</> google-services.json not found at {$source}");
            return;
        }

        $destDir = base_path('src-tauri/gen/android/app');
        if (!is_dir($destDir)) {
            $this->cmd->line("  <fg=yellow>→</> src-tauri/gen/android/app missing — run 'nativeblade:add android' first");
            return;
        }

        copy($source, $destDir . '/google-services.json');
        $this->cmd->line("  <fg=green>✓</> google-services.json copied to Android project");

        $this->ensureGoogleServicesPlugin();
    }

    private function ensureGoogleServicesPlugin(): void
    {
        $appGradle = base_path('src-tauri/gen/android/app/build.gradle.kts');
        if (!file_exists($appGradle)) return;

        $content = file_get_contents($appGradle);
        $changed = false;

        if (!str_contains($content, 'com.google.gms.google-services')) {
            $content = preg_replace(
                '/(plugins\s*\{[^}]*?)(\n\})/s',
                "$1\n    id(\"com.google.gms.google-services\")$2",
                $content,
                1
            );
            $changed = true;
        }

        if ($changed) {
            file_put_contents($appGradle, $content);
            $this->cmd->line("  <fg=green>✓</> google-services Gradle plugin enabled");
        }

        $rootGradle = base_path('src-tauri/gen/android/build.gradle.kts');
        if (!file_exists($rootGradle)) return;

        $root = file_get_contents($rootGradle);

        if (str_contains($root, 'com.google.gms:google-services') || str_contains($root, 'com.google.gms.google-services')) {
            return;
        }

        if (preg_match('/plugins\s*\{/', $root)) {
            $root = preg_replace(
                '/(plugins\s*\{)/',
                "$1\n    id(\"com.google.gms.google-services\") version \"4.4.4\" apply false",
                $root,
                1
            );
            file_put_contents($rootGradle, $root);
            $this->cmd->line("  <fg=green>✓</> google-services plugin declared in root build.gradle.kts");
            return;
        }

        if (preg_match('/buildscript\s*\{.*?dependencies\s*\{/s', $root)) {
            $root = preg_replace(
                '/(buildscript\s*\{.*?dependencies\s*\{)(\s*\n)/s',
                "$1$2        classpath(\"com.google.gms:google-services:4.4.4\")\n",
                $root,
                1
            );
            file_put_contents($rootGradle, $root);
            $this->cmd->line("  <fg=green>✓</> google-services classpath added to root build.gradle.kts");
            return;
        }

        $this->cmd->line("  <fg=yellow>→</> could not auto-patch root build.gradle.kts — add `classpath(\"com.google.gms:google-services:4.4.4\")` to the buildscript.dependencies block manually");
    }

}
