// Notification action
// Uses: ctx.notificationApi, ctx.isTauri, ctx.isAndroid, ctx.ensureChannel, ctx.post

export async function notification(payload, ctx) {
    const title = payload.title || 'NativeBlade';
    if (ctx.isTauri && ctx.notificationApi) {
        let granted = await ctx.notificationApi.isPermissionGranted();
        if (!granted) {
            const perm = await ctx.notificationApi.requestPermission();
            granted = perm === 'granted';
        }
        if (!granted) return;
        const opts = { title, body: payload.body || '' };
        if (payload.sound) opts.sound = payload.sound;
        if (payload.icon) {
            opts.icon = payload.icon;
        } else if (ctx.isAndroid) {
            // Default Android small icon — monochrome silhouette
            // generated by nativeblade:icon into drawable-*/ic_notification.png.
            // Without this, Tauri falls back to a generic info icon.
            opts.icon = 'ic_notification';
        }
        if (payload.channel) {
            opts.channelId = payload.channel;
            await ctx.ensureChannel(payload.channel);
        }
        ctx.notificationApi.sendNotification(opts);
    } else {
        ctx.post('nativeblade-alert', { message: payload.body });
    }
}
